seed: 0
run_mode: 'train'
output_dir: './output'  # 当前不支持自定义修改，请勿修改该默认值
load_checkpoint: '/home/ma-user/work/ckpt/glm2_6b.ckpt'
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# ==== context config ====
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "30GB"  # 59GB for 910B
  save_graphs: False
  device_id: 0

# aicc
remote_save_url: "Please input obs url on AICC platform."

# ==== model config ====
model:
  model_config:
    type: ChatGLM2Config
    batch_size: 4   # only for incremental infer
    num_layers: 28
    padded_vocab_size: 65024
    hidden_size: 4096
    ffn_hidden_size: 13696
    kv_channels: 128
    num_attention_heads: 32
    seq_length:  769
    #type: 指定模型配置的类型。
    #batch_size: 每次训练迭代处理的样本数量，仅用于增量推理。
    #num_layers: Transformer模型的层数，影响模型的深度和复杂度。
    #padded_vocab_size: 模型可以处理的独特词汇数量，包括填充和特殊标记。
    #hidden_size: 每层的神经元数量，影响模型的容量和计算复杂度。
    #ffn_hidden_size: 前馈神经网络的隐藏层大小，提高模型的表达能力。
    #kv_channels: 注意力机制中键和值矩阵的通道数，增加注意力机制的表达能力。
    #num_attention_heads: 多头注意力机制中的头数量，提高模型的性能。
    #seq_length: 模型可以处理的最大序列长度，允许处理更长的输入文本。
    hidden_dropout: 0.0
    attention_dropout: 0.0
    layernorm_epsilon: 1e-5
    rmsnorm: True
    apply_residual_connection_post_layernorm: False
    post_layer_norm: True
    add_bias_linear: False
    add_qkv_bias: True
    bias_dropout_fusion: True
    multi_query_attention: True
    multi_query_group_num: 2
    apply_query_key_layer_scaling: True
    attention_softmax_in_fp32: True
    fp32_residual_connection: False
    quantization_bit: 0
    pre_seq_len: None
    prefix_projection: False
    param_init_type: "float16"
    compute_dtype: "float16"
    layernorm_compute_type: "float32"
    use_past: False
    eos_token_id: 2
    pad_token_id: 0
    repetition_penalty: 1.0
    max_decode_length: 256
    checkpoint_name_or_path: "glm2_6b"
    top_k: 1
    top_p: 1
    do_sample: True
    pet_config:
      pet_type: lora
      # configuration of lora
      lora_rank: 8
      lora_alpha: 32
      lora_dropout: 0.1
      target_modules: '.*query_key_value*'
  arch:
    type: ChatGLM2ForConditionalGeneration

trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'glm2_6b_lora'
# if True do, evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False
eval_step_interval: 500
eval_epoch_interval: -1

metric:
  type: ADGENMetric

processor:
  return_tensors: ms
  tokenizer:
    type: ChatGLM2Tokenizer
    bos_token: '<sop>'
    eos_token: '<eop>'
    end_token: '</s>'
    mask_token: '[MASK]'
    gmask_token: '[gMASK]'
    pad_token: '<pad>'
    unk_token: '<unk>'
  type: GLMProcessor

# ==== dataset config ====
train_dataset: &train_dataset
  data_loader:
    type: MedicalDataLoader
    dataset_dir: "/home/ma-user/work/data/medical/train.json"
    shuffle: True 
    # 是否对数据进行随机打乱，True表示在每个训练周期开始前打乱数据
    phase: "train" 
    # 当前数据加载器的阶段，这里是训练阶段。
    version: 2
    origin_columns: ["prompt", "answer"]  # 修改 origin_columns 列名
  tokenizer:
    type: ChatGLM2Tokenizer
    vocab_file: "/home/ma-user/work/tokenizer/tokenizer.model"
    
  input_columns: ["input_ids", "labels"]
  max_source_length: 256
  # 设置输入序列的最大长度
  max_target_length: 512
  # 设置输出序列的最大长度
  ignore_pad_token_for_loss: True
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 8
  repeat: 1
  numa_enable: False
  prefetch_size: 1
  seed: 0

train_dataset_task:
  type: KeyWordGenDataset
  dataset_config: *train_dataset

eval_dataset: &eval_dataset
  data_loader:
    type: MedicalDataLoader
    dataset_dir: "/home/ma-user/work/data/mdeical/dev.json"
    shuffle: False
    phase: "eval"
    version: 2
    origin_columns: ["prompt", "answer"]  # 修改 origin_columns 列名
  tokenizer:
    type: ChatGLM2Tokenizer
    vocab_file: "/home/ma-user/work/tonkenizer/tokenizer.model"
    
  max_source_length: 512
  # 设置输入序列的最大长度为512个标记符。
  max_target_length: 512
  # 设置输出序列的最大长度为512个标记符。

  ignore_pad_token_for_loss: True
  input_columns: ["input_ids", "labels"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 8
  repeat: 1
  numa_enable: False
  prefetch_size: 1
  seed: 0

eval_dataset_task:
  type: KeyWordGenDataset
  dataset_config: *eval_dataset

# ==== runner config ====
runner_config:
  epochs: 4
  batch_size: 8
  sink_mode: True
  sink_size: 4
  #epochs: 4
  # 设置训练轮数为4。模型将遍历整个训练数据集4次。
  #batch_size: 8
  # 设置批处理大小为8。每次训练迭代将处理8个样本。
  #sink_mode: True
  # 设置为True，启用数据下沉模式以提高性能。
  #sink_size: 4
  # 设置sink的大小为4。

runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 65536
    scale_factor: 2
    scale_window: 1000
  use_clip_grad: True

# lr sechdule
lr_schedule:
  type: polynomial
  learning_rate: 5.e-5
  lr_end: 1.e-6
  warmup_steps: 0
  total_steps: -1 # -1 means it will load the total steps of the dataset
layer_scale: False
layer_decay: 0.65

# optimizer
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.95
  eps: 1.e-8
  weight_decay: 0.1
lr_scale: False
lr_scale_factor: 256

# parallel config
use_parallel: True
parallel:
  parallel_mode: 1 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: False
  loss_repeated_mean: True
  enable_alltoall: False
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True  # optimizer shard
  strategy_ckpt_config:
    save_file: "./ckpt_strategy.ckpt"
    only_trainable_params: False # 设置成 False，才能在策略文件中保存所有参数
parallel_config:
  data_parallel: 8
  model_parallel: 1
  pipeline_stage: 1
  expert_parallel: 1
  micro_batch_num: 1
  vocab_emb_dp: True
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# moe
moe_config:
  expert_num: 1
  capacity_factor: 1.05
  aux_loss_factor: 0.05
  num_experts_chosen: 1

# recompute
recompute_config:
  recompute: True
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: True
profile_communication: True
profile_memory: True

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "glm2-6b-lora"
    save_checkpoint_steps: 1000
    keep_checkpoint_max: 1
    integrated_save: False
    async_save: False
  - type: ObsMonitor
    keep_last: False
eval_callbacks:
  - type: ObsMonitor
    keep_last: False
